name: Main - CI

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

  pull_request: null

  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run: docker/bin/cli.sh composer install
      - name: Test
        run: docker/bin/cli.sh test
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'contracts'
            split_repository: 'framework-contracts'
          - local_path: 'env-vars-manager'
            split_repository: 'framework-env-vars-manager'
          - local_path: 'projects'
            split_repository: 'framework-projects'
          - local_path: 'testing'
            split_repository: 'framework-testing'
          - local_path: 'console'
            split_repository: 'framework-console'
          - local_path: 'mysql-based-write-model'
            split_repository: 'framework-mysql-based-write-model'
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: "symplify/monorepo-split-github-action@ac9845270ef47266435b4f124b133a323619e738"
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          package_directory: 'project/packages/${{ matrix.package.local_path }}'
          repository_organization: 'saasformation'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: 'SaaSFormation'
          user_email: 'info@saasformation.com'
      - uses: "symplify/monorepo-split-github-action@ac9845270ef47266435b4f124b133a323619e738"
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'project/packages/${{ matrix.package.local_path }}'
          repository_organization: 'saasformation'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: 'SaaSFormation'
          user_email: 'info@saasformation.com'